"""V114 PPO v4 bounded residual action contract.

The residual policy never emits a complete strategy.  It selects one of eight
small, auditable edits to the action produced by the current neural expert.
``KEEP`` is the control action and is not counted against the daily budget.

This module deliberately has no dependency on any historical Kaggriculture
agent.  It contains only the action vocabulary and deterministic quota state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Mapping, Optional, Tuple, Union


class ResidualChannel(str, Enum):
    """Probability-ratio/KL accounting channel used by PPO."""

    NONE = "none"
    MARKET = "market"
    UNIT = "unit"
    HYBRID = "hybrid"


class ResidualType(str, Enum):
    """Concrete residual actions.

    There are eight non-KEEP actions.  UP/DOWN directions are separate policy
    actions but share the family-level daily limits specified in the v4 plan.
    """

    KEEP = "KEEP"
    MARKET_QTY_UP_1 = "MARKET_QTY_UP_1"
    MARKET_QTY_DOWN_1 = "MARKET_QTY_DOWN_1"
    DEFER_ONE_MARKET_ORDER = "DEFER_ONE_MARKET_ORDER"
    ADVANCE_ONE_SELL = "ADVANCE_ONE_SELL"
    CASH_TIER_UP_1 = "CASH_TIER_UP_1"
    CASH_TIER_DOWN_1 = "CASH_TIER_DOWN_1"
    REASSIGN_ONE_IDLE_UNIT = "REASSIGN_ONE_IDLE_UNIT"
    TERMINAL_RETURN_OR_SELL = "TERMINAL_RETURN_OR_SELL"


# A short alias is convenient for callers and keeps the vocabulary explicit.
ResidualAction = ResidualType


@dataclass(frozen=True)
class ResidualSpec:
    kind: ResidualType
    family: str
    daily_limit: Optional[int]
    channel: ResidualChannel

    @property
    def is_keep(self) -> bool:
        return self.kind is ResidualType.KEEP

    @property
    def modifies_market(self) -> bool:
        return self.channel in (ResidualChannel.MARKET, ResidualChannel.HYBRID)

    @property
    def modifies_unit(self) -> bool:
        return self.channel in (ResidualChannel.UNIT, ResidualChannel.HYBRID)


RESIDUAL_SPECS: Dict[ResidualType, ResidualSpec] = {
    ResidualType.KEEP: ResidualSpec(
        ResidualType.KEEP, "KEEP", None, ResidualChannel.NONE
    ),
    ResidualType.MARKET_QTY_UP_1: ResidualSpec(
        ResidualType.MARKET_QTY_UP_1, "MARKET_QTY", 2, ResidualChannel.MARKET
    ),
    ResidualType.MARKET_QTY_DOWN_1: ResidualSpec(
        ResidualType.MARKET_QTY_DOWN_1, "MARKET_QTY", 2, ResidualChannel.MARKET
    ),
    ResidualType.DEFER_ONE_MARKET_ORDER: ResidualSpec(
        ResidualType.DEFER_ONE_MARKET_ORDER,
        "DEFER_ONE_MARKET_ORDER",
        1,
        ResidualChannel.MARKET,
    ),
    ResidualType.ADVANCE_ONE_SELL: ResidualSpec(
        ResidualType.ADVANCE_ONE_SELL,
        "ADVANCE_ONE_SELL",
        1,
        ResidualChannel.MARKET,
    ),
    ResidualType.CASH_TIER_UP_1: ResidualSpec(
        ResidualType.CASH_TIER_UP_1, "CASH_TIER", 1, ResidualChannel.MARKET
    ),
    ResidualType.CASH_TIER_DOWN_1: ResidualSpec(
        ResidualType.CASH_TIER_DOWN_1, "CASH_TIER", 1, ResidualChannel.MARKET
    ),
    ResidualType.REASSIGN_ONE_IDLE_UNIT: ResidualSpec(
        ResidualType.REASSIGN_ONE_IDLE_UNIT,
        "REASSIGN_ONE_IDLE_UNIT",
        1,
        ResidualChannel.UNIT,
    ),
    ResidualType.TERMINAL_RETURN_OR_SELL: ResidualSpec(
        ResidualType.TERMINAL_RETURN_OR_SELL,
        "TERMINAL_RETURN_OR_SELL",
        2,
        ResidualChannel.HYBRID,
    ),
}


_ALIASES = {
    "MARKET_QTY_UP": ResidualType.MARKET_QTY_UP_1,
    "MARKET_QTY_DOWN": ResidualType.MARKET_QTY_DOWN_1,
    "CASH_TIER_UP": ResidualType.CASH_TIER_UP_1,
    "CASH_TIER_DOWN": ResidualType.CASH_TIER_DOWN_1,
    "DEFER": ResidualType.DEFER_ONE_MARKET_ORDER,
    "ADVANCE_SELL": ResidualType.ADVANCE_ONE_SELL,
    "REASSIGN_IDLE_UNIT": ResidualType.REASSIGN_ONE_IDLE_UNIT,
    "TERMINAL": ResidualType.TERMINAL_RETURN_OR_SELL,
}


def normalize_residual_type(value: Union[ResidualType, str]) -> ResidualType:
    if isinstance(value, ResidualType):
        return value
    if not isinstance(value, str):
        raise ValueError(f"residual type must be a string or ResidualType, got {type(value)!r}")
    name = value.strip().upper().replace("-", "_").replace(" ", "_")
    if name in _ALIASES:
        return _ALIASES[name]
    try:
        return ResidualType[name]
    except KeyError:
        try:
            return ResidualType(name)
        except ValueError as exc:
            raise ValueError(f"unknown residual type: {value!r}") from exc


@dataclass(frozen=True)
class ResidualRequest:
    """A residual edit plus the minimum targeting information it needs.

    ``candidate_action`` is required for CASH_TIER edits because changing the
    tier itself does not map directly to a Kaggriculture atomic action.  It must
    be an action generated by the same current neural policy under the adjusted
    tier.  TERMINAL edits may use either ``candidate_action`` or a targeted
    ``replacement``/``market_order``.
    """

    kind: ResidualType = ResidualType.KEEP
    market_index: Optional[int] = None
    unit_index: Optional[int] = None  # -1 means farmer; 0..N-1 mean hands.
    replacement: Any = None
    market_order: Any = None
    candidate_action: Optional[Mapping[str, Any]] = None
    quantity_step: int = 1
    metadata: Mapping[str, Any] = field(default_factory=dict)

    @property
    def spec(self) -> ResidualSpec:
        return RESIDUAL_SPECS[self.kind]

    @property
    def channel(self) -> ResidualChannel:
        return self.spec.channel

    @classmethod
    def from_value(cls, value: Any) -> "ResidualRequest":
        if isinstance(value, cls):
            return value
        if isinstance(value, (ResidualType, str)):
            return cls(kind=normalize_residual_type(value))
        if not isinstance(value, Mapping):
            raise ValueError("residual request must be a ResidualRequest, string, enum, or mapping")

        raw_kind = value.get("kind", value.get("type", value.get("residual", "KEEP")))
        payload = value.get("payload")
        merged: Dict[str, Any] = dict(payload) if isinstance(payload, Mapping) else {}
        merged.update(value)

        market_index = merged.get(
            "market_index", merged.get("order_index", merged.get("target_index"))
        )
        unit_index = merged.get("unit_index", merged.get("hand_index"))
        unit_target = merged.get("unit", merged.get("unit_target"))
        if unit_index is None and isinstance(unit_target, str):
            target = unit_target.strip().lower()
            if target == "farmer":
                unit_index = -1
            elif target.startswith("hand:"):
                unit_index = target.split(":", 1)[1]

        known = {
            "kind", "type", "residual", "payload", "market_index", "order_index",
            "target_index", "unit_index", "hand_index", "unit", "unit_target",
            "replacement", "unit_action", "market_order", "candidate_action",
            "quantity_step", "step",
        }
        metadata = {key: val for key, val in merged.items() if key not in known}
        try:
            market_index = None if market_index is None else int(market_index)
            unit_index = None if unit_index is None else int(unit_index)
            quantity_step = max(1, int(merged.get("quantity_step", merged.get("step", 1))))
        except (TypeError, ValueError) as exc:
            raise ValueError("residual indices and quantity_step must be integers") from exc

        return cls(
            kind=normalize_residual_type(raw_kind),
            market_index=market_index,
            unit_index=unit_index,
            replacement=merged.get("replacement", merged.get("unit_action")),
            market_order=merged.get("market_order"),
            candidate_action=merged.get("candidate_action"),
            quantity_step=quantity_step,
            metadata=metadata,
        )


def residual_spec(value: Any) -> ResidualSpec:
    return RESIDUAL_SPECS[ResidualRequest.from_value(value).kind]


class DailyResidualQuota:
    """Tracks successful residual edits for one episode day.

    A day change resets all counters.  Callers should reserve only after every
    safety check succeeds; :meth:`consume` combines the check and increment.
    KEEP always succeeds and never consumes quota.
    """

    def __init__(self, max_non_keep: int = 4) -> None:
        if int(max_non_keep) < 0:
            raise ValueError("max_non_keep must be non-negative")
        self.max_non_keep = int(max_non_keep)
        self.day: Any = None
        self.non_keep_count = 0
        self.family_counts: Dict[str, int] = {}

    def reset(self, day: Any = None) -> None:
        self.day = day
        self.non_keep_count = 0
        self.family_counts = {}

    def _roll_day(self, day: Any) -> None:
        if self.day != day:
            self.reset(day)

    def can_consume(self, residual: Any, day: Any) -> Tuple[bool, str]:
        self._roll_day(day)
        spec = residual_spec(residual)
        if spec.is_keep:
            return True, "keep"
        if self.non_keep_count >= self.max_non_keep:
            return False, "daily_non_keep_limit"
        used = self.family_counts.get(spec.family, 0)
        if spec.daily_limit is not None and used >= spec.daily_limit:
            return False, f"daily_{spec.family.lower()}_limit"
        return True, "ok"

    # Compatibility-friendly spelling for policy masks.
    can_apply = can_consume

    def consume(self, residual: Any, day: Any) -> Tuple[bool, str]:
        allowed, reason = self.can_consume(residual, day)
        if not allowed:
            return False, reason
        spec = residual_spec(residual)
        if not spec.is_keep:
            self.non_keep_count += 1
            self.family_counts[spec.family] = self.family_counts.get(spec.family, 0) + 1
        return True, "applied" if not spec.is_keep else "keep"

    def snapshot(self) -> Dict[str, Any]:
        return {
            "day": self.day,
            "max_non_keep": self.max_non_keep,
            "non_keep_count": self.non_keep_count,
            "family_counts": dict(self.family_counts),
        }


# Backwards-friendly alias for concise callers.
ResidualQuota = DailyResidualQuota


__all__ = [
    "DailyResidualQuota",
    "RESIDUAL_SPECS",
    "ResidualAction",
    "ResidualChannel",
    "ResidualQuota",
    "ResidualRequest",
    "ResidualSpec",
    "ResidualType",
    "normalize_residual_type",
    "residual_spec",
]
