#!/usr/bin/env python3
"""Build the self-contained RC9 submission artifact and manifest."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
RC8_SOURCE = HERE.parents[1] / "rc8_parametric_search" / "candidate" / "candidate.py"
OVERLAY = HERE / "overlay.py"
OUTPUT = HERE / "main.py"
MANIFEST = HERE / "manifest.json"


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def load_module(path: Path, name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def build() -> dict[str, Any]:
    base = RC8_SOURCE.read_text(encoding="utf-8")
    overlay = OVERLAY.read_text(encoding="utf-8")
    header = (
        "# AUTO-GENERATED by rc9_opponent_path_predictor/model/packager.py\n"
        "# Self-contained Kaggle artifact; edit overlay.py, not this file.\n\n"
    )
    source = header + base.rstrip() + "\n\n" + overlay.rstrip() + "\n"
    compile(source, str(OUTPUT), "exec")
    temporary = OUTPUT.with_name(OUTPUT.name + ".tmp")
    temporary.write_text(source, encoding="utf-8")
    os.replace(temporary, OUTPUT)

    module = load_module(OUTPUT, "rc9_packaged_main")
    payload = {
        "schema": "v116-rc9-model-manifest-v1",
        "model": "v116_rc9_opponent_path_predictor",
        "status": "MECHANISM_IMPLEMENTED_NOT_BENCHMARKED",
        "parent_source": str(RC8_SOURCE.relative_to(HERE.parents[4])),
        "parent_source_sha256": sha256_bytes(base.encode("utf-8")),
        "overlay_sha256": sha256_bytes(overlay.encode("utf-8")),
        "main_sha256": sha256_bytes(source.encode("utf-8")),
        "default_config": "p0064_3f0eb3eec9",
        "default_params_hash": module.DEFAULT_PARAMS_HASH,
        "router_depth": module.RC9_ROUTER_DEPTH,
        "modes": list(module.RC9_MODES),
        "interfaces": ["build_executor(params, mode)", "executor.diagnostics()", "make_agent()"],
        "information_boundary": {
            "public_current_and_past_only": True,
            "replay_actions": False,
            "future_state": False,
            "opponent_private_state": False,
            "parent_agent": False,
        },
        "evaluation": {"games": 0, "gold_claim": False},
    }
    temporary_manifest = MANIFEST.with_name(MANIFEST.name + ".tmp")
    temporary_manifest.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    os.replace(temporary_manifest, MANIFEST)
    return payload


if __name__ == "__main__":
    print(json.dumps(build(), ensure_ascii=False, indent=2))
