from pathlib import Path
import json,hashlib,zipfile,datetime,statistics
G=Path(__file__).resolve().parent;B=G.parent
s=json.loads((G/'summary.json').read_text());gate=s['gate'];fresh=s['fresh'];dev=s['development'];b=gate['aggregates']['v127b'];fb=fresh['aggregates']['v127b'];a=fresh['aggregates']['v127a'];t=fresh['aggregates']['time_tasks'];old=json.loads((B.parent/'v127a_neural_daily_tasks/gate_y68_20260915/summary.json').read_text());oldgroups={x['opponent']:x for x in old['summaries']}
lines=['# V127b：资金可持续性修复与完整门控','',f"完成：{datetime.datetime.now(datetime.timezone.utc).isoformat()}。",'',f"**25 个 y68 模型，16 seed 双席位，V127b {b['wins']}/{b['games']} 胜；门控{'通过' if gate['gate_pass'] else '未通过'}。本轮另有 32 局开发对照和 192 局新 seed 确认。**",'', '## 模型堆栈和归因边界','', 'V127b = V127a 原网络及权重（658,905 参数）→ 每日生产/工人/土地目标 → 跨日雇工和饲料预算 → 劳力与增长期限检查 → 实际状态任务执行 → 成交缺口反馈。', '', '本版没有训练新权重。执行器收到反馈后调整当前可执行任务，网络仍每天推理一次；没有新增神经反馈输入或日内网络重规划。收益变化不能归因为网络重新学会了预算。固定日计划只作对照，不作为 V127 神经谱系候选。', '', '## 开发对照（相同 2 seed、双席位、y68a/y68v）','', '| 方案 | 局数 | 胜场 | 平均现金 | 平均胜差 | 逃逸/局 | 缺水/局 |','|---|---:|---:|---:|---:|---:|---:|']
names={'v127a':'V127a 原版','reserve_only':'原网络＋只加跨日资金预算','v127b':'V127b 完整执行器','time_tasks':'固定日计划＋同一完整执行器'}
def row(k,r):return f"| {names[k]} | {r['games']} | {r['wins']} | {r['mean_cash']:,.1f} | {r['mean_margin']:+,.1f} | {r['mean_escapes']:.3f} | {r['mean_drought']:.3f} |"
for k,r in dev['aggregates'].items():lines.append(row(k,r))
lines += ['', '开发面板只有 2 个独立 seed，用于功能归因，不能作为强度证明。只加预算的平均胜差 -113,852.9，比完整版的 -126,441.9 更好；完整版只是预先安排的接口实验，不是经证实的本批最强竞技方案。完整执行器还包含采购顺序、劳力准入和增长期限，不能把相对预算版的变化归给其中某一个单独机制。预算单改未做新 seed 确认，结论仍有限。', '', '## 独立新 seed 确认（16 seed、双席位、y68a/y68v）','', '| 方案 | 局数 | 胜场 | 平均现金 | 平均胜差 | 逃逸/局 | 缺水/局 |','|---|---:|---:|---:|---:|---:|---:|']
for k,r in fresh['aggregates'].items():lines.append(row(k,r))
lines += ['', '| 配对比较 | 平均现金变化 | 按 seed 分块的探索性 95% 区间 | 平均胜差变化 |','|---|---:|---|---:|']
for key,c in fresh['paired_comparisons'].items():
 lo,hi=c['own_cash']['exploratory_seed_bootstrap_95'];lines.append(f"| {key} | {c['own_cash']['mean_paired_delta']:+,.1f} | [{lo:+,.1f}, {hi:+,.1f}] | {c['margin']['mean_paired_delta']:+,.1f} |")
lines += ['', '每个 seed 的两个席位和两个对手先合并成一个区块，再抽样。只有 16 个独立 seed；区间为探索性结果，不把 64 局当成 64 个独立环境。新 seed 在实现冻结之后运行，没有用其结果修改代码。神经计划相对固定日计划的现金优势区间包含零，平均胜差点估计更差，胜差区间也包含零；因此本轮没有证明神经计划有额外竞技价值。', '', '## y68 全家族门控','', '同 V127a 的 25 个冻结源码模型；seed1100–1115 为历史基准，非新的留出。全部完整策略动态执行，采用官方最后 callable 入口。每个对手 32/32 严格胜出才通过，平局不计胜。', '', '| 对手 | V127b 胜/平/负 | 胜率 | V127b 平均现金 | 平均胜差 | 相对 A 现金变化 | V127b 轨迹一致性 |','|---|---:|---:|---:|---:|---:|---:|']
for g in gate['groups']:
 og=oldgroups[g['opponent']];lines.append(f"| {g['opponent']} | {g['wins']}/{g['draws']}/{g['losses']} | {g['win_rate']:.1%} | {g['mean_cash']:,.0f} | {g['mean_margin']:+,.0f} | {g['mean_cash']-og['mean_cash']:+,.0f} | {g['trajectory']['unit_hash']['mean']:.4f} |")
c=gate['paired_comparisons']['v127b_minus_v127a'];lines += ['',f"全门控平均现金 {b['mean_cash']:,.1f}，对 A 配对变化 {c['own_cash']['mean_paired_delta']:+,.1f}；平均胜差 {b['mean_margin']:+,.1f}，配对变化 {c['margin']['mean_paired_delta']:+,.1f}。共享市场里自身现金改善与胜差改善应分别衡量。", '', '## 轨迹一致性','', '系数沿用 V127a：同一对手、同席位、不同 seed 的整队 farmer+hands 动作（含参数）逐步完全相等记 1，否则记 0。每个对手共 240 对、每对 719 步。全家族值按对手等权平均。', '', '| 指标 | V127a 历史门控 | V127b 同面板 |','|---|---:|---:|',f"| 整队动作 | {old['macro_trajectory_mean']:.4f} | {b['trajectory_consistency']:.4f} |",f"| 逐工人动作 | {old['macro_actor_mean']:.4f} | {b['per_actor_consistency']:.4f} |",f"| 市场单 | {old['macro_market_mean']:.4f} | {b['market_consistency']:.4f} |",f"| 整队＋市场 | {old['macro_full_mean']:.4f} | {b['full_action_consistency']:.4f} |",'', '1 表示被比较的动作轨迹完全一致，0 表示没有同一步的整队动作完全一致；它不证明是否使用 tape。低一致性不是训练奖励，不把动作分化等同竞争力。市场指标包含双空订单时刻。', '', '## 生存修复和单局证据','',f"完整门控：V127b 每局逃逸 {b['mean_escapes']:.3f}、缺水 {b['mean_drought']:.3f}；首日末零现金 {b['day0_zero_cash']}/{b['games']}，次日末零帮工 {b['day1_zero_hands']}/{b['games']}。",f"新 seed：V127b 每局逃逸 {fb['mean_escapes']:.3f}、缺水 {fb['mean_drought']:.3f}；原版分别 {a['mean_escapes']:.3f}、{a['mean_drought']:.3f}。", '', '同一 y68a / seed1100 / 席位0：V127a 首日末现金 0、次日无工人；V127b 首日末现金 380、次日末 404，均有 4 名帮工，第 3 天仍有 4 人。原版连续逃逸，V127b 保住了牲畜。', '', '这个示例中 V127b 的终局现金 37,430，略低于 V127a 的 37,782；对手现金从 186,072 降至 136,044，胜差因此改善。它说明修复生存不保证每个 seed 的自身现金更高，也不应只选有利单局展示。完整逐日对照见 `opening_comparison.json`。', '', '## 验证','', '- 32 开发＋800 门控＋192 新 seed，共 1024 个正式评估记录；两个额外逐步复现仅作验证，不混入胜率分母。', '- 候选、权重及全部对手哈希在确认前后保持一致。网络权重与 V127a 相同。', '- 6 项原执行器回归＋8 项预算/期限/反馈测试通过。', '- 原版控制入口与历史对局 719 步动作和终局奖励完全一致；开发后零数量反馈计数修正也通过完整单局动作一致性复核。', '- 官方 Python 1.32.7 引擎，无动作异常回退。未施加 Kaggle 容器超时，仅为本地结果；没有线上提交或 Rating 结论。', '', '## 下一步边界','', 'V127b 完成执行与可行性接口的第一轮改进。V127c 尚未实现，后续应针对自身状态学习可行增量计划，并保持执行器固定做神经决策价值对照。PPO 和日内神经重规划也未在本版实现。', '', '## 文件','', '- `plan.json`、`candidate_freeze.json`：预登记方案与冻结哈希。', '- `gate/summary.json`、`fresh/summary.json`：逐对手结果、配对差值和轨迹统计。', '- `*/games/*.json.gz`：完整动作、位置、日计划及反馈。', '- `reproduction.json`、`opening_comparison.json`：复核与具体失败链修复。']
(G/'REPORT.md').write_text('\n'.join(lines)+'\n')
short=['# V127b 实验结果','',f"V127b 对 25 个 y68 模型的 800 局门控：{b['wins']} 胜，{b['draws']} 平，{'通过' if gate['gate_pass'] else '未通过'}。",'', '网络权重与 V127a 相同，本版是资金预算和任务执行改进，不是新一轮神经网络训练。','', '| 面板/策略 | 局数 | 胜场 | 平均现金 | 平均胜差 | 逃逸/局 | 缺水/局 |','|---|---:|---:|---:|---:|---:|---:|',row('v127b',b)]
for k,r in fresh['aggregates'].items():short.append(row(k,r).replace('| '+names[k]+' |','| 新 seed / '+names[k]+' |',1))
short += ['',f"完整门控整队轨迹一致性：{b['trajectory_consistency']:.4f}（V127a：{old['macro_trajectory_mean']:.4f}）。",'', '详见 [完整报告](research/REPORT.md)。V127a 保留，V127c 尚未实现；未提交 Kaggle。']
(B/'RESULTS.md').write_text('\n'.join(short)+'\n')
rpath=B.parent/'v127_family.json';reg=json.loads(rpath.read_text());entry=next(v for v in reg['variants'] if v['id']=='v127b');entry['status']='GATE_PASSED' if gate['gate_pass'] else 'CASHFLOW_REPAIR_VALIDATED_Y68_GATE_FAILED';entry['gate_results']=b;entry['fresh_results']=fresh['aggregates'];rpath.write_text(json.dumps(reg,indent=2,ensure_ascii=False))
freeze=json.loads((G/'candidate_freeze.json').read_text());assert all(hashlib.sha256((B/f).read_bytes()).hexdigest()==h for f,h in freeze.items())
manifest=json.loads((B/'deployment_manifest.json').read_text())
with zipfile.ZipFile(B/'v127b_policy_bundle.zip') as z:
 assert set(z.namelist())==set(manifest['runtime_files'])
 for fn,h in manifest['runtime_files'].items():assert hashlib.sha256(z.read(fn)).hexdigest()==h
val={'evaluated_games':1024,'gate_games':800,'fresh_games':192,'development_games':32,'all_done':all(p['all_done'] for p in s.values()),'freeze_unchanged':True,'weights_unchanged':True,'executor_tests_passed':6,'budget_tests_passed':8,'reproduction':json.loads((G/'reproduction.json').read_text()),'bundle_valid':True,'no_submission':True}
(G/'validation.json').write_text(json.dumps(val,indent=2));(G/'artifact_hashes.json').write_text(json.dumps({f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in [G/'evaluate.py',G/'summarize.py',G/'write_report.py',G/'summary.json',G/'REPORT.md',G/'candidate_freeze.json']},indent=2));print('reports and registry finalized')
