#!/usr/bin/env python3
from __future__ import annotations
import concurrent.futures,importlib.util,json,os,statistics
from pathlib import Path
HERE=Path(__file__).resolve().parent;MODEL=HERE.parent;SCHEMA='kaggriculture-v94-preconstruction-audit-v1';spec=importlib.util.spec_from_file_location('v94base',MODEL/'v88_reference_trajectory_state_tube_moe/audit_and_screen.py');base=importlib.util.module_from_spec(spec);assert spec and spec.loader;spec.loader.exec_module(base);base.HERE=HERE;base.POLICIES={'full':HERE/'main.py','ablation':HERE/'ablation_main.py','comparator':MODEL/'v76_adjacent_safe_buy_lead/main.py'};base.SEEDS=tuple(range(94101,94117))
def play(t):return base.play(t)
def main():
 tasks=[(m,f,s,t) for m in base.POLICIES for f in base.OPPONENTS for s in base.SEEDS for t in (0,1)]
 with concurrent.futures.ProcessPoolExecutor(max_workers=min(16,os.cpu_count() or 1)) as p:rows=list(p.map(play,tasks,chunksize=1))
 scores={m:statistics.mean(r['score'] for r in rows if r['mode']==m) for m in base.POLICIES};families={m:{f:statistics.mean(r['score'] for r in rows if r['mode']==m and r['family']==f) for f in base.OPPONENTS} for m in base.POLICIES};full=[r for r in rows if r['mode']=='full'];comp=[r for r in rows if r['mode']=='comparator'];changed_games=sum(int(r.get('stats',{}).get('changed_calls',0))>0 for r in full);changed_calls=sum(int(r.get('stats',{}).get('changed_calls',0)) for r in full);eg={};ec={}
 for r in full:
  for e,n in (r.get('stats',{}).get('experts',{}) or {}).items():ec[e]=ec.get(e,0)+int(n);eg[e]=eg.get(e,0)+int(int(n)>0)
 fa=base.paired(rows,'full','ablation');fc=base.paired(rows,'full','comparator');arch=base.static_audit();cc=statistics.mean(r['margin'] < -10000 for r in full);pc=statistics.mean(r['margin'] < -10000 for r in comp);safety=sum(r['violations'] for r in rows);all719=all(r['calls']==719 for r in rows);gate=bool(not arch['complete_agent_call_detected'] and all719 and safety==0 and changed_games>=8 and fa['uplift_pp']>0 and fa['positive_zero_negative'][0]>fa['positive_zero_negative'][2] and scores['full']>=.60 and families['full']['v76']>=.50 and 100*(cc-pc)<=1)
 x={'schema':SCHEMA,'engine':str(base.kagsim.ENGINE_VERSION),'official_replay_sources_consumed':0,'synthetic_seed_range':[min(base.SEEDS),max(base.SEEDS)],'games':len(rows),'static_architecture_audit':arch,'score_rate':scores,'score_rate_by_opponent':families,'full_vs_ablation':fa,'full_vs_comparator':fc,'direct_v76_score_rate':families['full']['v76'],'candidate_catastrophic_rate':cc,'comparator_catastrophic_rate':pc,'catastrophic_rate_delta_pp':100*(cc-pc),'changed_market_games':changed_games,'changed_market_calls':changed_calls,'expert_game_coverage':eg,'expert_call_coverage':ec,'all_719_calls':all719,'safety_violations':safety,'fallback_calls_full':sum(int(r.get('stats',{}).get('fallback',0)) for r in full),'decision':'PASS_PRECONSTRUCTION' if gate else 'REJECT_PRECONSTRUCTION','rows':rows};(HERE/'preconstruction_audit_results.json').write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in x.items() if k!='rows'},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
