"""Create D2 counterfactual labels by replaying and forking daily states.

The input is produced by :mod:`collect_states`.  For every retained snapshot
we reconstruct its source prefix, verify both the state and action-prefix
fingerprints, then branch complete production experts plus at most one market
expert.  This produces *relative* outcomes against E_V1/M_NONE rather than a
behaviour-cloning label.

Important Kaggle-environments detail: ``Environment.clone()`` does not retain
``env.info`` (which carries the Kaggriculture random seed).  ``fork_env``
therefore creates a fresh environment object and explicitly deep-copies
``info``, state, steps, logs, and configuration.  Expert state is separately
snapshotted/restored through ``Catalog.snapshot``.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
from pathlib import Path
from typing import Any, Iterable, Mapping

import numpy as np

from action_compiler import ActionCompiler
from catalog import Catalog
from collect_states import (
    DEFAULT_MARKET,
    DEFAULT_PRODUCTION,
    SCHEMA_VERSION_STATES,
    _action_digest,
    _day,
    _opponent_factory,
    canonical_json,
    stable_hash,
)
from features import FEATURE_DIM, FEATURE_NAMES, SCHEMA_VERSION


SCHEMA_VERSION_CF = "kaggriculture-ppo-v3-counterfactual-d2-1"


def fork_env(env):
    """Fork an environment without losing Kaggriculture's RNG-bearing info.

    Direct ``env.clone()`` is insufficient because the upstream clone
    constructor initialises ``info`` to an empty dict.  This helper copies all
    mutable simulation state explicitly.  It never shares lists/dicts with the
    source branch, so one candidate cannot contaminate another candidate.
    """
    child = env.clone()
    child.info = copy.deepcopy(env.info)
    child.configuration = copy.deepcopy(env.configuration)
    child.state = copy.deepcopy(env.state)
    child.steps = copy.deepcopy(env.steps)
    child.logs = copy.deepcopy(env.logs)
    return child


def _route_agent(catalog: Catalog, expert_id: str):
    try:
        return getattr(catalog, {"E_V1": "v1", "E_HIGH": "high"}[expert_id])
    except KeyError:
        raise ValueError("unknown production expert: %s" % expert_id)


def _set_steps(env, step: int) -> None:
    env.state[0].observation.step = int(step)
    env.state[1].observation.step = int(step)


def _history_observation(env, step: int, seat: int):
    # ``steps`` contains states before the actions at each turn.  We restore
    # the explicit step anyway: collectors intentionally set it to avoid a
    # version-dependent off-by-one in local Kaggle environments.
    obs = copy.deepcopy(env.steps[int(step)][int(seat)]["observation"])
    obs.step = int(step)
    return obs


def _hydrate_catalog(catalog: Catalog, env, seat: int, until_step: int) -> None:
    """Replay expert-local state without re-stepping the environment."""
    for step in range(int(until_step)):
        obs = _history_observation(env, step, seat)
        # Every complete plan receives the same past observations.  Their
        # modules are isolated, so this does not impose a V1 default path.
        catalog.v1(obs)
        catalog.low(obs)
        catalog.high(obs)


def _hydrate_opponent(opponent, env, seat: int, until_step: int) -> None:
    for step in range(int(until_step)):
        opponent(_history_observation(env, step, 1 - int(seat)))


def _rebuild_prefix(row: Mapping[str, Any]):
    """Replay the immutable source prefix and reject non-reproducible rows."""
    from kaggle_environments import make

    seed, seat, fork_step = int(row["seed"]), int(row["seat"]), int(row["step"])
    source_expert, opponent_id = str(row["source_expert"]), str(row["opponent_id"])
    if source_expert != "E_V1":
        # D2 labels use the V1 anchor at the *same* state.  Allowing a source
        # prefix generated by another production template would quietly change
        # the counterfactual estimand.
        raise ValueError("D2 source_expert must be E_V1, got %s" % source_expert)
    env = make("kaggriculture", configuration={"seed": seed}, debug=False)
    env.reset(2)
    source_catalog = Catalog("rebuild_source_%s" % row["state_id"])
    source = _route_agent(source_catalog, source_expert)
    opponent = _opponent_factory(opponent_id, "rebuild_opponent_%s" % row["state_id"])
    trace: list[dict[str, str]] = []
    for step in range(fork_step):
        _set_steps(env, step)
        own = source(env.state[seat].observation)
        other = opponent(env.state[1 - seat].observation)
        actions = [own, other] if seat == 0 else [other, own]
        trace.append({"seat0": _action_digest(actions[0]), "seat1": _action_digest(actions[1])})
        env.step(actions)
    _set_steps(env, fork_step)
    obs = env.state[seat].observation
    got_state_hash, got_prefix_hash = stable_hash(obs), stable_hash(trace)
    if got_state_hash != str(row["state_hash"]):
        raise RuntimeError("state fingerprint mismatch for %s" % row["state_id"])
    if got_prefix_hash != str(row["prefix_hash"]):
        raise RuntimeError("prefix fingerprint mismatch for %s" % row["state_id"])
    # The source catalog is already hydrated from real calls.  Other experts
    # need their own state history, which is reconstructed from the immutable
    # environment history rather than copied from V1.
    flat_catalog = Catalog("fork_catalog_%s" % row["state_id"])
    _hydrate_catalog(flat_catalog, env, seat, fork_step)
    return env, flat_catalog.snapshot()


def _score(own: float, other: float) -> float:
    return 1.0 if own > other else 0.0 if own < other else 0.5


def _run_branch(
    *,
    source_env,
    catalog_snapshot: Mapping[str, Any],
    row: Mapping[str, Any],
    production_id: str,
    market_id: str,
    horizon_days: int,
    persistent_production: bool,
) -> dict[str, Any]:
    """Run one decision branch to terminal.

    Production is a one-off commitment at step 72, so a day-3 production
    branch must remain active to terminal.  A market expert is a daily
    residual and is active only for the registered finite horizon.  Keeping
    these two scopes separate is essential: treating a route as a one-day
    perturbation trains labels for an action the submitted policy can never
    deploy.
    """
    env = fork_env(source_env)
    seat, fork_step = int(row["seat"]), int(row["step"])
    fork_day = int(row["day"])
    catalog = Catalog("branch_%s_%s_%s" % (row["state_id"], production_id, market_id))
    catalog.restore(catalog_snapshot)
    opponent = _opponent_factory(str(row["opponent_id"]), "branch_opp_%s_%s_%s" % (row["state_id"], production_id, market_id))
    _hydrate_opponent(opponent, source_env, seat, fork_step)
    compiler = ActionCompiler()
    effective = False
    footprint_rows: list[dict[str, Any]] = []
    error = None
    try:
        for step in range(fork_step, 719):
            _set_steps(env, step)
            obs = env.state[seat].observation
            baseline = catalog.baseline(obs)
            if not baseline.eligible or baseline.plan is None:
                raise RuntimeError("E_V1 baseline unavailable")
            day = _day(obs, step)
            market_active = fork_day <= day < fork_day + int(horizon_days)
            production_active = persistent_production and day >= fork_day
            if production_active:
                production = baseline if production_id == "E_V1" else catalog.production_proposal(production_id, obs)
            else:
                production = baseline
            if market_active:
                market_expert, market = catalog.market_proposal(market_id, obs, production)
            else:
                market_expert, market = None, None
            compiled = compiler.compile(
                obs,
                baseline_action=baseline.plan.action,
                production=production,
                market_expert=market_expert,
                market=market,
            )
            if production_active or market_active:
                effective = effective or compiled.effective_intervention
                footprint_rows.append(compiled.audit_row())
            other = opponent(env.state[1 - seat].observation)
            actions = [compiled.action, other] if seat == 0 else [other, compiled.action]
            env.step(actions)
    except Exception as exc:  # errors are labels/audit data, never silently baseline-filled
        error = "%s:%s" % (type(exc).__name__, exc)
    statuses = [str(state.status) for state in env.state]
    rewards = [float(state.reward or 0.0) for state in env.state]
    own, other = rewards[seat], rewards[1 - seat]
    return {
        "production_id": production_id,
        "market_id": market_id,
        "effective_action_change": bool(effective),
        "footprints": footprint_rows,
        "status": statuses,
        "terminal_liquidation_ok": statuses == ["DONE", "DONE"] and error is None,
        "error": error,
        "final_gold": own,
        "opponent_gold": other,
        "gold_margin": own - other,
        "score": _score(own, other),
    }


def _read_rows(states_file: Path, max_states: int | None = None) -> list[dict[str, Any]]:
    rows = [json.loads(line) for line in states_file.read_text(encoding="utf-8").splitlines() if line.strip()]
    for row in rows:
        if row.get("schema") != SCHEMA_VERSION_STATES:
            raise ValueError("unexpected input schema")
        if len(row.get("features", [])) != FEATURE_DIM:
            raise ValueError("feature dimension mismatch for %s" % row.get("state_id"))
    rows.sort(key=lambda row: (row["seed"], row["seat"], row["step"], row["state_id"]))
    return rows[:max_states] if max_states is not None else rows


def _write_npz(
    rows: list[Mapping[str, Any]],
    production_ids: tuple[str, ...],
    market_ids: tuple[str, ...],
    output: Path,
) -> None:
    n, p, m = len(rows), len(production_ids), len(market_ids)
    features = np.asarray([row["features"] for row in rows], dtype=np.float32)
    production_mask = np.zeros((n, p), dtype=np.bool_)
    market_mask = np.zeros((n, m), dtype=np.bool_)
    production_uplift = np.full((n, p), np.nan, dtype=np.float32)
    market_uplift = np.full((n, m), np.nan, dtype=np.float32)
    effective = np.zeros((n, p, m), dtype=np.bool_)
    score_uplift = np.full((n, p, m), np.nan, dtype=np.float32)
    margin_uplift = np.full((n, p, m), np.nan, dtype=np.float32)
    for index, row in enumerate(rows):
        branches = {(b["production_id"], b["market_id"]): b for b in row["branches"]}
        anchor = branches.get(("E_V1", "M_NONE"))
        if anchor is None or anchor.get("error") is not None:
            continue
        # Full production plans are only selectable at the day-3 commitment
        # point.  Later daily states intentionally carry no production label.
        route_decision = int(row.get("day", -1)) == 3
        for pi, production_id in enumerate(production_ids):
            branch = branches.get((production_id, "M_NONE"))
            if branch is not None and branch.get("error") is None:
                changed = bool(branch.get("effective_action_change", False))
                if route_decision and (production_id == "E_V1" or changed):
                    production_mask[index, pi] = True
                    production_uplift[index, pi] = float(branch["score"] - anchor["score"])
        for mi, market_id in enumerate(market_ids):
            branch = branches.get(("E_V1", market_id))
            if branch is not None and branch.get("error") is None:
                changed = bool(branch.get("effective_action_change", False))
                if market_id == "M_NONE" or changed:
                    market_mask[index, mi] = True
                    market_uplift[index, mi] = float(branch["score"] - anchor["score"])
        for pi, production_id in enumerate(production_ids):
            for mi, market_id in enumerate(market_ids):
                branch = branches.get((production_id, market_id))
                if branch is None or branch.get("error") is not None:
                    continue
                effective[index, pi, mi] = bool(branch.get("effective_action_change", False))
                score_uplift[index, pi, mi] = float(branch["score"] - anchor["score"])
                margin_uplift[index, pi, mi] = float(branch["gold_margin"] - anchor["gold_margin"])
    output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output,
        features=features,
        production_mask=production_mask,
        market_mask=market_mask,
        production_uplift=production_uplift,
        market_uplift=market_uplift,
        pair_ids=np.asarray([str(row["pair_id"]) for row in rows]),
        pair_id=np.asarray([str(row["pair_id"]) for row in rows]),
        source=np.asarray([str(row["source"]) for row in rows]),
        family=np.asarray([str(row["strategy_family"]) for row in rows]),
        strategy_family=np.asarray([str(row["strategy_family"]) for row in rows]),
        episode_id=np.asarray([str(row["episode_id"]) for row in rows]),
        opponent_id=np.asarray([str(row["opponent_id"]) for row in rows]),
        seed=np.asarray([int(row["seed"]) for row in rows], dtype=np.int64),
        seat=np.asarray([int(row["seat"]) for row in rows], dtype=np.int8),
        split=np.asarray([str(row["split"]) for row in rows]),
        day=np.asarray([int(row["day"]) for row in rows], dtype=np.int8),
        step=np.asarray([int(row["step"]) for row in rows], dtype=np.int16),
        state_ids=np.asarray([str(row["state_id"]) for row in rows]),
        production_ids=np.asarray(production_ids),
        market_ids=np.asarray(market_ids),
        # ``*_names`` are the training/runtime contract; ``*_ids`` remain
        # available for human inspection and backward-compatible readers.
        production_names=np.asarray(production_ids),
        market_names=np.asarray(market_ids),
        score_uplift=score_uplift,
        margin_uplift=margin_uplift,
        effective_action_change=effective,
    )


def fork_counterfactuals(
    *,
    states_file: Path,
    output_dir: Path,
    production_ids: Iterable[str] = DEFAULT_PRODUCTION,
    market_ids: Iterable[str] = DEFAULT_MARKET,
    horizon_days: int = 1,
    max_states: int | None = None,
    start_index: int = 0,
) -> dict[str, Any]:
    """Generate the compact D2 tensor schema required by Router training."""
    production_ids, market_ids = tuple(production_ids), tuple(market_ids)
    if "E_V1" not in production_ids or "M_NONE" not in market_ids:
        raise ValueError("D2 must include E_V1/M_NONE comparison anchor")
    if not 1 <= int(horizon_days) <= 7:
        raise ValueError("horizon_days must be 1..7")
    invalid_p = set(production_ids) - set(DEFAULT_PRODUCTION)
    invalid_m = set(market_ids) - set(DEFAULT_MARKET)
    if invalid_p or invalid_m:
        raise ValueError("unregistered experts: production=%r market=%r" % (sorted(invalid_p), sorted(invalid_m)))
    all_rows = _read_rows(Path(states_file))
    start_index = int(start_index)
    if start_index < 0 or start_index > len(all_rows):
        raise ValueError("start_index outside available states")
    rows = all_rows[start_index:]
    if max_states is not None:
        rows = rows[:max_states]
    results: list[dict[str, Any]] = []
    errors = 0
    for index, state in enumerate(rows, 1):
        result = dict(state)
        branches = []
        try:
            source_env, catalog_snapshot = _rebuild_prefix(state)
            for production_id in production_ids:
                for market_id in market_ids:
                    branch = _run_branch(
                        source_env=source_env, catalog_snapshot=catalog_snapshot, row=state,
                        production_id=production_id, market_id=market_id, horizon_days=int(horizon_days),
                        persistent_production=int(state["day"]) == 3,
                    )
                    branches.append(branch)
                    errors += int(branch["error"] is not None)
        except Exception as exc:
            errors += 1
            branches.append({
                "production_id": "E_V1", "market_id": "M_NONE", "effective_action_change": False,
                "footprints": [], "status": [], "terminal_liquidation_ok": False,
                "error": "%s:%s" % (type(exc).__name__, exc),
                "final_gold": float("nan"), "opponent_gold": float("nan"), "gold_margin": float("nan"), "score": float("nan"),
            })
        result["branches"] = branches
        results.append(result)
        print(json.dumps({"phase": "fork", "completed": index, "states": len(rows), "branches": len(branches), "errors": errors}), flush=True)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    details = output_dir / "counterfactual_rows.jsonl"
    details.write_text("".join(canonical_json(row) + "\n" for row in results), encoding="utf-8")
    dataset = output_dir / "d2_counterfactual.npz"
    _write_npz(results, production_ids, market_ids, dataset)
    finite_branches = [branch for row in results for branch in row["branches"] if branch.get("error") is None]
    report = {
        "schema": SCHEMA_VERSION_CF,
        "feature_schema": SCHEMA_VERSION,
        "feature_dim": FEATURE_DIM,
        "feature_names": FEATURE_NAMES,
        "states": len(results),
        "start_index": start_index,
        "branches": len(finite_branches),
        "errors": errors,
        "production_ids": list(production_ids),
        "market_ids": list(market_ids),
        "horizon_days": int(horizon_days),
        "production_scope": "day3_commitment_to_terminal",
        "market_scope": "finite_daily_residual",
        "files": {
            "rows": details.name,
            "dataset": dataset.name,
            "rows_sha256": hashlib.sha256(details.read_bytes()).hexdigest(),
            "dataset_sha256": hashlib.sha256(dataset.read_bytes()).hexdigest(),
        },
        "tensor_schema": {
            "features": ["N", "F"],
            "production_mask": ["N", "P"],
            "market_mask": ["N", "M"],
            "production_uplift": ["N", "P"],
            "market_uplift": ["N", "M"],
            "pair_ids": ["N"], "source": ["N"], "family": ["N"], "opponent_id": ["N"],
            "seed": ["N"], "seat": ["N"], "day": ["N"], "step": ["N"], "split": ["N"],
        },
        "acceptance": {
            "all_states_have_anchor": all(any(b["production_id"] == "E_V1" and b["market_id"] == "M_NONE" and b.get("error") is None for b in row["branches"]) for row in results),
            "zero_errors": errors == 0,
            "all_features_finite": bool(np.isfinite(np.asarray([row["features"] for row in results], dtype=np.float32)).all()) if results else True,
        },
    }
    (output_dir / "manifest.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent
    parser.add_argument("--states", type=Path, default=root / "data" / "d2_counterfactual" / "state_pilot" / "daily_states.jsonl")
    parser.add_argument("--output-dir", type=Path, default=root / "data" / "d2_counterfactual" / "fork_pilot")
    parser.add_argument("--production", nargs="+", choices=DEFAULT_PRODUCTION, default=list(DEFAULT_PRODUCTION))
    parser.add_argument("--market", nargs="+", choices=DEFAULT_MARKET, default=list(DEFAULT_MARKET))
    parser.add_argument("--horizon-days", type=int, default=1)
    parser.add_argument("--max-states", type=int)
    parser.add_argument("--start-index", type=int, default=0,
                        help="stable offset after state sorting; enables independent D2 shards")
    args = parser.parse_args()
    report = fork_counterfactuals(
        states_file=args.states, output_dir=args.output_dir, production_ids=args.production,
        market_ids=args.market, horizon_days=args.horizon_days, max_states=args.max_states,
        start_index=args.start_index,
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
