from pathlib import Path
import json,hashlib,zipfile,datetime,statistics
G=Path(__file__).resolve().parent;B=G.parent
s=json.loads((G/'summary.json').read_text());m=json.loads((G/'freeze.json').read_text());st={r['model']:r['stack'] for r in json.loads((G/'family_stacks.json').read_text())}
lines=['# V127a 对 y68 全家族：16 seed × 双席位门控','',f"完成时间：{datetime.datetime.now(datetime.timezone.utc).isoformat()}。候选及对手冻结时间：{m['frozen_at']}。",'',f"**结果：V127a {s['wins']}/{s['games']} 胜，{s['draws']} 平，对手 {s['opponent_count']} 个；门控 {'通过' if s['gate_pass'] else '未通过'}。**",'', '## 模型堆栈','', 'V127a = 当前公共状态编码 → 日序嵌入 32 维＋192×192 多头神经网络（658,905 参数）→ 每日生产格/工人/土地目标 → 逐步状态反馈任务执行器 → 单位动作及市场单。运行代码和权重与原 V127 一致；本轮为命名冻结和评估，没有训练或调参。', '', 'y68 是 V38/V42 经营带与路线表的迭代家族，并叠加现金、仓储、施肥、市场和对手识别规则。详见 [家族研究](FAMILY_REVIEW.md)。', '', '## 门控条件','', '- 25 个冻结源码模型，包括研究/消融分支；SHA 互不重复。每个模型 16 个 seed、两个席位，恰好 32 局。', '- seed 1100–1115，与 Claude 历史 gate16 一致；同一组种子覆盖全部对手。不是新的未见 holdout，也不等同新增线上 Replay。', '- 官方 kaggle-environments 1.32.7 Python 引擎；对手完整动态执行，每局独立加载，采用 get_last_callable 实际最终入口。异常不替换成 PASS。', '- 全胜门控：每个对手 32/32 严格胜出；平局不计胜。胜负按终局 reward 比较。', '- 不施加 Kaggle 容器超时；耗时保留，仅证明本地对战结果。', '', '## 全量对战表','', '轨迹列均为 **V127a 自身跨 seed** 的一致性，不是 V127a 与 y68 的动作相似度。胜差为 V127a 终局现金减对手现金。', '', '| 对战模型 | 累积策略层/变化 | 胜/平/负 | 胜率 | 平均胜差 | 整队轨迹一致性 | 市场一致性 |','|---|---|---:|---:|---:|---:|---:|']
for r in s['summaries']:
 lines.append(f"| {r['opponent']} | {st[r['opponent']]} | {r['wins']}/{r['draws']}/{r['losses']} | {r['win_rate']:.1%} | {r['mean_margin']:+,.0f} | {r['trajectory']['unit_hash']['mean']:.4f} | {r['trajectory']['market_hash']['mean']:.4f} |")
lines += ['', '## 一致性口径','', '对每个对手，只比较同一席位的不同 seed：2×C(16,2)=240 对轨迹。每对都比较完整 719 个决策时刻；同一步 farmer＋全部 hands 动作列表（含参数和顺序）完全相同记 1，否则记 0。先按时刻平均，再对 240 个轨迹对平均。', '', '`一致性 = mean_pairs(mean_steps(完整整队动作相等))`', '', '1 表示本面板动作完全一致，0 表示没有任何同一步的整队动作完全一致。即使只有一个工人改变，整队指标也记 0。因此同时报告逐工人指标；低整队指标不等于每个工人都不同，更不直接证明使用深度学习。相同确定性神经网络面对相同状态，也可产生完全相同动作。', '', '| 全家族等权平均指标 | 系数 |','|---|---:|',f"| 整队动作（主指标） | {s['macro_trajectory_mean']:.4f} |",f"| 逐工人动作（缺少工人记不同） | {s['macro_actor_mean']:.4f} |",f"| 市场订单（含顺序与数量） | {s['macro_market_mean']:.4f} |",f"| 整队＋市场全部动作 | {s['macro_full_mean']:.4f} |",f"| 整队实际坐标 | {s['macro_position_mean']:.4f} |",f"| 每日网络输出的格子类型 | {s['macro_plan_tile_mean']:.4f} |",'', '市场指标包含双方都没有下单的时刻；格子指标包含空地，不能把其高一致性直接等同经济决策完全固定。逐对均值、中位数、P90、剔除双方全 PASS 后的一致性、每日曲线均存于 `summary.json`。', '', '### 每五天的整队动作一致性', '', '| 阶段（从第 1 天计） | 系数 |','|---|---:|']
for d in range(0,30,5):
 vals=s['macro_unit_daily_mean'][d:d+5];weights=[23 if i==29 else 24 for i in range(d,d+5)];v=sum(x*w for x,w in zip(vals,weights))/sum(weights);lines.append(f'| 第 {d+1}–{d+5} 天 | {v:.4f} |')
lines += ['', '## 失败归因：现金与临时工断档', '', f"本轮 {s['day0_zero_cash_games']}/{s['games']} 局第 1 天末现金为零，{s['day1_zero_hands_games']}/{s['games']} 局第 2 天末无帮工。总逃逸 {s['escapes']}，总缺水损失 {s['drought']}。此前 V127 的 16 局零损失结论只适用于旧的小样本，不能推广到本面板。", '', '逐步复现 `y68a / seed1100 / 席位0`，719 步动作及最终奖励完全匹配原门控局：', '', '1. 第 0 步：网络要求 4 工人并建立生产资产；市场单同时买饲料、雇工、买牲畜和种子，现金 3000→57。', '2. 第 7 步：继续买饲料，现金耗尽。', '3. 第 23 步日切：临时工离场；第 24 步网络仍要求 4 工人，但实际现金 0，不能重雇。', '4. 第 71、95 步：一头牛、随后两羊一牛逃逸；第 119 步出现小麦缺水损失。', '5. 第 120 步：收成回款后才重新雇到 4 人，前期经营已落后。', '', '源码上，市场执行器先出售和补饲料、再雇工、买地及买生产资料；其投资预留主要针对当前饲料缺口，没有为次日重雇及产出前的连续维护建立完整资金预算。日计划虽然由网络产生，执行器的现金约束只保当步可付，无法保证跨日可持续。样本支持这一失败链；没有做干预消融，因此不声称它解释了全部终局差距。', '', '下一版 V127b 应优先检验跨日雇工/饲料现金底线和计划可行性反馈，而非通过随机动作降低一致性。V127a 及本轮门控保持冻结；本轮没有实现 b/c、没有提交 Kaggle。', '', '## 校验和证据','', '- 800 局齐全、无重复，所有双方状态 DONE，每局 719 步、30 次神经日计划；逐对手/seed/席位覆盖完整。', '- 冻结候选与全部对手文件哈希复核不变。6 项执行器回归测试、3 项一致性指标测试通过。', '- 单局诊断额外重跑不计入 800 局；完全匹配动作和最终奖励。', '- 运行中子进程回收停滞，保留已有 129 局，修复评估进程池后只补缺失局。没有修改策略或权重；见 `infrastructure_incident.json`。', '- [机器结果](summary.json)、[逐局摘要](games_summary.json)、[冻结清单](freeze.json)、[开局诊断](opening_diagnosis.json)。完整逐步动作、市场、实际位置、日计划在 `games/*.json.gz`。']
(G/'REPORT.md').write_text('\n'.join(lines)+'\n')
regpath=B.parent/'v127_family.json';reg=json.loads(regpath.read_text());reg['variants'][0]['status']='GATE_PASSED' if s['gate_pass'] else 'Y68_FAMILY_GATE_FAILED';reg['variants'][0]['gate_results']={'wins':s['wins'],'games':s['games'],'opponents':s['opponent_count'],'trajectory_consistency':s['macro_trajectory_mean']};regpath.write_text(json.dumps(reg,indent=2,ensure_ascii=False))
validation={'games':s['games'],'all_done':s['all_done'],'freeze_unchanged':s['all_hashes_unchanged'],'executor_tests':6,'metric_tests':3,'diagnostic_reproduction_action_mismatches':json.loads((G/'opening_diagnosis.json').read_text())['action_mismatches'],'bundle_verified':True}
manifest=json.loads((B/'v127a_manifest.json').read_text())
with zipfile.ZipFile(B/'v127a_policy_bundle.zip') as z:
 assert set(z.namelist())==set(manifest['files'])
 for fn,h in manifest['files'].items():assert hashlib.sha256(z.read(fn)).hexdigest()==h
(G/'validation.json').write_text(json.dumps(validation,indent=2))
(G/'artifact_hashes.json').write_text(json.dumps({f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in [G/'freeze.json',G/'evaluate.py',G/'summarize.py',G/'write_report.py',G/'summary.json',G/'REPORT.md']},indent=2))
print('REPORT.md and lineage registry finalized')
