#!/usr/bin/env python3
"""V21 candidate: strict out-of-fold exact/lattice target-frequency XGBoost.

Leakage contract
----------------
1. ``id`` and ``addicted_label`` are removed before any feature builder runs.
2. For an outer fold, target statistics for outer-train rows are generated by
   an inner StratifiedKFold. Outer-valid and test rows are mapped only from the
   outer-train labels.
3. Combined train+test frequency features use key codes only. No target array is
   accepted by that code path.
4. XGBoost uses a fixed number of rounds. Outer-valid labels evaluate the model
   but never choose a checkpoint.

The default command is the full five-fold job. Use ``--smoke`` for the small,
fast pipeline and leakage-mutation audit used before a full retrain.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
import tempfile
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, train_test_split


ROOT = Path(__file__).resolve().parents[3]
DATA_DIR = ROOT / "data"
DEFAULT_OUT_DIR = Path(__file__).resolve().parent

TARGET = "addicted_label"
ID_COL = "id"
FORBIDDEN_FEATURES = {ID_COL, TARGET}
SEED = 42

NUMERIC_COLS = [
    "age",
    "daily_screen_time_hours",
    "social_media_hours",
    "gaming_hours",
    "work_study_hours",
    "sleep_hours",
    "notifications_per_day",
    "app_opens_per_day",
    "weekend_screen_time",
]
CAT_COLS = ["gender", "stress_level", "academic_work_impact"]
FLOAT_LATTICE_COLS = [
    "daily_screen_time_hours",
    "social_media_hours",
    "gaming_hours",
    "work_study_hours",
    "sleep_hours",
    "weekend_screen_time",
]
TOP_SCREEN_COLS = [
    "daily_screen_time_hours",
    "social_media_hours",
    "weekend_screen_time",
]
COMPONENT_COLS = ["social_media_hours", "gaming_hours", "work_study_hours"]
PAIR_LATTICES = [
    ("daily_screen_time_hours", "social_media_hours"),
    ("social_media_hours", "weekend_screen_time"),
    ("daily_screen_time_hours", "weekend_screen_time"),
]

MISSING_INT = np.iinfo(np.int64).min


@dataclass(frozen=True)
class KeySpec:
    """One equality/lattice key and its fold-local target prior."""

    name: str
    kind: str
    alpha: float
    parent: str | None = None


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def assert_feature_frame(frame: pd.DataFrame, context: str) -> None:
    forbidden = FORBIDDEN_FEATURES.intersection(frame.columns)
    if forbidden:
        raise AssertionError(f"{context} 含禁用字段: {sorted(forbidden)}")
    if frame.columns.duplicated().any():
        duplicates = frame.columns[frame.columns.duplicated()].tolist()
        raise AssertionError(f"{context} 含重复字段: {duplicates}")


def load_data() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    train = pd.read_csv(DATA_DIR / "train.csv")
    test = pd.read_csv(DATA_DIR / "test.csv")
    sample = pd.read_csv(DATA_DIR / "sample_submission.csv")
    if TARGET not in train or TARGET in test:
        raise ValueError("训练/测试目标字段不符合预期")
    if train[ID_COL].duplicated().any() or test[ID_COL].duplicated().any():
        raise ValueError("id 不唯一")
    if not sample[ID_COL].equals(test[ID_COL]):
        raise ValueError("sample_submission 与 test id 顺序不一致")
    expected = NUMERIC_COLS + CAT_COLS
    if [c for c in train.columns if c not in {ID_COL, TARGET}] != expected:
        raise ValueError("训练特征字段或顺序发生变化")
    if [c for c in test.columns if c != ID_COL] != expected:
        raise ValueError("测试特征字段或顺序发生变化")
    return train, test, sample


def smoke_sample(
    train: pd.DataFrame,
    test: pd.DataFrame,
    sample: pd.DataFrame,
    train_rows: int,
    test_rows: int,
    seed: int,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    if train_rows < len(train):
        selected, _ = train_test_split(
            np.arange(len(train)),
            train_size=train_rows,
            stratify=train[TARGET].to_numpy(),
            random_state=seed,
        )
        selected = np.sort(selected)
        train = train.iloc[selected].reset_index(drop=True)
    if test_rows < len(test):
        rng = np.random.default_rng(seed)
        selected_test = np.sort(rng.choice(len(test), size=test_rows, replace=False))
        test = test.iloc[selected_test].reset_index(drop=True)
        sample = sample.iloc[selected_test].reset_index(drop=True)
    if not sample[ID_COL].equals(test[ID_COL]):
        raise AssertionError("smoke 抽样后 sample/test id 未对齐")
    return train, test, sample


def quantized_key(series: pd.Series, multiplier: float) -> np.ndarray:
    """Return an exact integer coordinate with an explicit missing sentinel."""
    values = series.to_numpy(dtype=np.float64)
    output = np.full(len(values), MISSING_INT, dtype=np.int64)
    valid = np.isfinite(values)
    output[valid] = np.rint(values[valid] * multiplier).astype(np.int64)
    return output


def factorize_joint(
    train_parts: list[np.ndarray], test_parts: list[np.ndarray]
) -> tuple[np.ndarray, np.ndarray, int]:
    """Factorize equality groups jointly without reading a target."""
    if len(train_parts) != len(test_parts) or not train_parts:
        raise ValueError("joint factorization parts 不一致")
    combined_parts = [
        np.concatenate([train_part, test_part])
        for train_part, test_part in zip(train_parts, test_parts)
    ]
    if len(combined_parts) == 1:
        values: Any = combined_parts[0]
    else:
        values = pd.MultiIndex.from_arrays(combined_parts)
    codes, uniques = pd.factorize(values, sort=True, use_na_sentinel=False)
    codes = codes.astype(np.int32, copy=False)
    train_size = len(train_parts[0])
    return codes[:train_size], codes[train_size:], int(len(uniques))


def build_key_codes(
    train_features: pd.DataFrame, test_features: pd.DataFrame
) -> tuple[pd.DataFrame, pd.DataFrame, list[KeySpec], dict[str, int]]:
    """Build transductive equality codes from feature values only.

    Joint factorization is allowed because it only defines equality groups. It
    never reads ``y`` and cannot create a target statistic.
    """
    assert_feature_frame(train_features, "key train input")
    assert_feature_frame(test_features, "key test input")
    if list(train_features.columns) != list(test_features.columns):
        raise ValueError("key train/test columns 不一致")

    train_codes: dict[str, np.ndarray] = {}
    test_codes: dict[str, np.ndarray] = {}
    level_counts: dict[str, int] = {}
    specs: list[KeySpec] = []

    def register(
        name: str,
        train_parts: list[np.ndarray],
        test_parts: list[np.ndarray],
        *,
        kind: str,
        alpha: float,
        parent: str | None = None,
    ) -> None:
        if name in train_codes:
            raise ValueError(f"重复 key: {name}")
        if parent is not None and parent not in train_codes:
            raise ValueError(f"parent 必须先注册: {name} -> {parent}")
        train_code, test_code, n_levels = factorize_joint(train_parts, test_parts)
        train_codes[name] = train_code
        test_codes[name] = test_code
        level_counts[name] = n_levels
        specs.append(KeySpec(name=name, kind=kind, alpha=alpha, parent=parent))

    # Multi-resolution parents are registered before their exact children.
    r05_values: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    for col in TOP_SCREEN_COLS:
        r05_values[col] = (
            quantized_key(train_features[col], 2.0),
            quantized_key(test_features[col], 2.0),
        )
        register(
            f"r05_{col}",
            [r05_values[col][0]],
            [r05_values[col][1]],
            kind="round_0.5",
            alpha=30.0,
        )

    r01_values: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    for col in FLOAT_LATTICE_COLS:
        r01_values[col] = (
            quantized_key(train_features[col], 10.0),
            quantized_key(test_features[col], 10.0),
        )
        parent = f"r05_{col}" if col in TOP_SCREEN_COLS else None
        register(
            f"r01_{col}",
            [r01_values[col][0]],
            [r01_values[col][1]],
            kind="round_0.1",
            alpha=15.0,
            parent=parent,
        )

    # Exact official features. Float exactness is represented on the 0.01 grid.
    for col in NUMERIC_COLS:
        multiplier = 100.0 if col in FLOAT_LATTICE_COLS else 1.0
        parent = f"r01_{col}" if col in FLOAT_LATTICE_COLS else None
        register(
            f"exact_{col}",
            [quantized_key(train_features[col], multiplier)],
            [quantized_key(test_features[col], multiplier)],
            kind="exact_numeric",
            alpha=10.0,
            parent=parent,
        )
    for col in CAT_COLS:
        register(
            f"exact_{col}",
            [train_features[col].fillna("__NA__").astype(str).to_numpy()],
            [test_features[col].fillna("__NA__").astype(str).to_numpy()],
            kind="exact_categorical",
            alpha=30.0,
        )

    # High-coverage 0.1-grid interactions found in the local data audit.
    for left, right in PAIR_LATTICES:
        register(
            f"pair01_{left}__{right}",
            [r01_values[left][0], r01_values[right][0]],
            [r01_values[left][1], r01_values[right][1]],
            kind="pair_round_0.1",
            alpha=10.0,
        )

    train_complete_sum = train_features[COMPONENT_COLS].sum(axis=1, min_count=3)
    test_complete_sum = test_features[COMPONENT_COLS].sum(axis=1, min_count=3)
    train_other = train_features["daily_screen_time_hours"] - train_complete_sum
    test_other = test_features["daily_screen_time_hours"] - test_complete_sum
    register(
        "r01_other_screen_complete",
        [quantized_key(train_other, 10.0)],
        [quantized_key(test_other, 10.0)],
        kind="structural_round_0.1",
        alpha=15.0,
    )

    train_frame = pd.DataFrame(train_codes, dtype=np.int32)
    test_frame = pd.DataFrame(test_codes, dtype=np.int32)
    if list(train_frame.columns) != list(test_frame.columns):
        raise AssertionError("key code columns 不一致")
    return train_frame, test_frame, specs, level_counts


def build_unsupervised_global_frequency(
    train_keys: pd.DataFrame,
    test_keys: pd.DataFrame,
    specs: list[KeySpec],
    level_counts: dict[str, int],
) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Combined train+test log-frequency; target is absent by construction."""
    total_rows = len(train_keys) + len(test_keys)
    train_output = np.empty((len(train_keys), len(specs)), dtype=np.float32)
    test_output = np.empty((len(test_keys), len(specs)), dtype=np.float32)
    names: list[str] = []
    for col_idx, spec in enumerate(specs):
        train_code = train_keys[spec.name].to_numpy(dtype=np.int64)
        test_code = test_keys[spec.name].to_numpy(dtype=np.int64)
        counts = np.bincount(
            np.concatenate([train_code, test_code]),
            minlength=level_counts[spec.name],
        )
        train_output[:, col_idx] = np.log(
            (counts[train_code] + 1.0) / (total_rows + 1.0)
        ).astype(np.float32)
        test_output[:, col_idx] = np.log(
            (counts[test_code] + 1.0) / (total_rows + 1.0)
        ).astype(np.float32)
        names.append(f"global_logfreq_{spec.name}")
    if not np.isfinite(train_output).all() or not np.isfinite(test_output).all():
        raise AssertionError("global frequency 包含非法值")
    return train_output, test_output, names


def encode_query_from_fit(
    fit_keys: pd.DataFrame,
    query_keys: pd.DataFrame,
    y_fit: np.ndarray,
    specs: list[KeySpec],
    level_counts: dict[str, int],
) -> tuple[np.ndarray, list[str]]:
    """Map a query using target/count statistics from ``fit`` only."""
    y_fit = np.asarray(y_fit, dtype=np.float64)
    if len(fit_keys) != len(y_fit):
        raise ValueError("target encoding fit keys/y 长度不一致")
    if len(y_fit) == 0 or not set(np.unique(y_fit)).issubset({0.0, 1.0}):
        raise ValueError("target encoding y_fit 非法")
    prior = float(y_fit.mean())
    spec_by_name = {spec.name: spec for spec in specs}
    stats: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    for spec in specs:
        codes = fit_keys[spec.name].to_numpy(dtype=np.int64)
        counts = np.bincount(codes, minlength=level_counts[spec.name]).astype(
            np.float64
        )
        sums = np.bincount(
            codes,
            weights=y_fit,
            minlength=level_counts[spec.name],
        ).astype(np.float64)
        stats[spec.name] = counts, sums

    posterior_cache: dict[str, np.ndarray] = {}

    def posterior(name: str) -> np.ndarray:
        if name in posterior_cache:
            return posterior_cache[name]
        spec = spec_by_name[name]
        query_code = query_keys[name].to_numpy(dtype=np.int64)
        counts, sums = stats[name]
        if spec.parent is None:
            parent_prior: np.ndarray | float = prior
        else:
            parent_prior = posterior(spec.parent)
        result = (
            sums[query_code] + spec.alpha * parent_prior
        ) / (counts[query_code] + spec.alpha)
        posterior_cache[name] = result
        return result

    output = np.empty((len(query_keys), 2 * len(specs)), dtype=np.float32)
    names: list[str] = []
    for spec_idx, spec in enumerate(specs):
        query_code = query_keys[spec.name].to_numpy(dtype=np.int64)
        counts, _ = stats[spec.name]
        output[:, 2 * spec_idx] = posterior(spec.name).astype(np.float32)
        # Normalize by fit size so inner-OOF and outer-valid/test scales match.
        output[:, 2 * spec_idx + 1] = np.log(
            (counts[query_code] + 1.0) / (len(y_fit) + 1.0)
        ).astype(np.float32)
        names.extend([f"te_{spec.name}", f"fit_logfreq_{spec.name}"])
    if not np.isfinite(output).all():
        raise AssertionError("fold target/frequency encoding 包含非法值")
    return output, names


def build_outer_encoded_features(
    train_keys: pd.DataFrame,
    test_keys: pd.DataFrame,
    outer_fit_idx: np.ndarray,
    outer_valid_idx: np.ndarray,
    y_outer_fit: np.ndarray,
    specs: list[KeySpec],
    level_counts: dict[str, int],
    inner_folds: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, list[str], dict[str, Any]]:
    """Produce inner-OOF outer-train and pure outer-valid/test encodings.

    The API intentionally receives ``y_outer_fit`` rather than full ``y``. It
    has no way to inspect an outer-validation label.
    """
    fit_keys = train_keys.iloc[outer_fit_idx].reset_index(drop=True)
    valid_keys = train_keys.iloc[outer_valid_idx].reset_index(drop=True)
    query_test = test_keys.reset_index(drop=True)
    y_outer_fit = np.asarray(y_outer_fit, dtype=np.int8)
    if len(fit_keys) != len(y_outer_fit):
        raise ValueError("outer fit keys/y 长度不一致")

    splitter = StratifiedKFold(
        n_splits=inner_folds,
        shuffle=True,
        random_state=seed,
    )
    inner_oof = np.empty((len(fit_keys), 2 * len(specs)), dtype=np.float32)
    assignments = np.zeros(len(fit_keys), dtype=np.int8)
    feature_names: list[str] | None = None
    inner_priors: list[float] = []

    for inner_fit_idx, inner_valid_idx in splitter.split(
        np.zeros(len(y_outer_fit)), y_outer_fit
    ):
        encoded, names = encode_query_from_fit(
            fit_keys.iloc[inner_fit_idx].reset_index(drop=True),
            fit_keys.iloc[inner_valid_idx].reset_index(drop=True),
            y_outer_fit[inner_fit_idx],
            specs,
            level_counts,
        )
        inner_oof[inner_valid_idx] = encoded
        assignments[inner_valid_idx] += 1
        inner_priors.append(float(y_outer_fit[inner_fit_idx].mean()))
        if feature_names is None:
            feature_names = names
        elif feature_names != names:
            raise AssertionError("inner feature names 漂移")

    if not np.all(assignments == 1):
        raise AssertionError("inner OOF 行未被恰好编码一次")
    valid_encoded, valid_names = encode_query_from_fit(
        fit_keys,
        valid_keys,
        y_outer_fit,
        specs,
        level_counts,
    )
    test_encoded, test_names = encode_query_from_fit(
        fit_keys,
        query_test,
        y_outer_fit,
        specs,
        level_counts,
    )
    if feature_names != valid_names or feature_names != test_names:
        raise AssertionError("outer feature names 不一致")
    audit = {
        "outer_fit_rows": int(len(fit_keys)),
        "outer_valid_rows": int(len(valid_keys)),
        "outer_prior": float(y_outer_fit.mean()),
        "inner_folds": int(inner_folds),
        "inner_prior_min": float(min(inner_priors)),
        "inner_prior_max": float(max(inner_priors)),
        "inner_assignment_min": int(assignments.min()),
        "inner_assignment_max": int(assignments.max()),
    }
    assert feature_names is not None
    return inner_oof, valid_encoded, test_encoded, feature_names, audit


def safe_ratio(num: pd.Series, den: pd.Series) -> pd.Series:
    return num / den.replace(0.0, np.nan)


def build_base_features(
    train_features: pd.DataFrame, test_features: pd.DataFrame
) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Label-free raw, structural, digit, and one-hot features."""
    assert_feature_frame(train_features, "base train input")
    assert_feature_frame(test_features, "base test input")

    def one(frame: pd.DataFrame) -> pd.DataFrame:
        out = frame[NUMERIC_COLS].astype(np.float32).copy()
        components = frame[COMPONENT_COLS]
        component_available = components.fillna(0.0).sum(axis=1)
        component_complete = components.sum(axis=1, min_count=3)
        out["component_sum_available"] = component_available
        out["component_sum_complete"] = component_complete
        out["other_screen_available"] = (
            frame["daily_screen_time_hours"] - component_available
        )
        out["other_screen_complete"] = (
            frame["daily_screen_time_hours"] - component_complete
        )
        out["n_components_observed"] = components.notna().sum(axis=1)
        out["weekend_minus_daily"] = (
            frame["weekend_screen_time"] - frame["daily_screen_time_hours"]
        )
        out["social_plus_gaming"] = (
            frame["social_media_hours"] + frame["gaming_hours"]
        )
        out["social_share"] = safe_ratio(
            frame["social_media_hours"], frame["daily_screen_time_hours"]
        )
        out["gaming_share"] = safe_ratio(
            frame["gaming_hours"], frame["daily_screen_time_hours"]
        )
        out["work_share"] = safe_ratio(
            frame["work_study_hours"], frame["daily_screen_time_hours"]
        )
        out["weekend_ratio"] = safe_ratio(
            frame["weekend_screen_time"], frame["daily_screen_time_hours"]
        )
        for col in FLOAT_LATTICE_COLS:
            cents = np.rint(frame[col].astype(np.float64) * 100.0)
            out[f"digit10_{col}"] = ((cents // 10) % 10).astype(np.float32)
            out[f"digit01_{col}"] = (cents % 10).astype(np.float32)
        out = out.replace([np.inf, -np.inf], np.nan).astype(np.float32)
        return out

    train_base = one(train_features)
    test_base = one(test_features)
    combined_cats = pd.concat(
        [train_features[CAT_COLS], test_features[CAT_COLS]],
        axis=0,
        ignore_index=True,
    )
    categorical_dummies = pd.get_dummies(
        combined_cats,
        columns=CAT_COLS,
        dummy_na=True,
        dtype=np.float32,
    )
    train_dummy = categorical_dummies.iloc[: len(train_features)].reset_index(drop=True)
    test_dummy = categorical_dummies.iloc[len(train_features) :].reset_index(drop=True)
    train_base = pd.concat([train_base.reset_index(drop=True), train_dummy], axis=1)
    test_base = pd.concat([test_base.reset_index(drop=True), test_dummy], axis=1)
    if list(train_base.columns) != list(test_base.columns):
        raise AssertionError("base train/test columns 不一致")
    assert_feature_frame(train_base, "built base train")
    return (
        train_base.to_numpy(dtype=np.float32),
        test_base.to_numpy(dtype=np.float32),
        train_base.columns.tolist(),
    )


def array_digest(values: np.ndarray) -> str:
    contiguous = np.ascontiguousarray(values)
    return hashlib.sha256(contiguous.view(np.uint8)).hexdigest()


def leakage_mutation_audit(
    train_keys: pd.DataFrame,
    test_keys: pd.DataFrame,
    y: np.ndarray,
    fit_idx: np.ndarray,
    valid_idx: np.ndarray,
    specs: list[KeySpec],
    level_counts: dict[str, int],
    inner_folds: int,
    seed: int,
) -> dict[str, Any]:
    """Demonstrate validation-label isolation and fit-label sensitivity."""
    original = build_outer_encoded_features(
        train_keys,
        test_keys,
        fit_idx,
        valid_idx,
        y[fit_idx],
        specs,
        level_counts,
        inner_folds,
        seed,
    )[:3]
    validation_mutated = y.copy()
    validation_mutated[valid_idx] = 1 - validation_mutated[valid_idx]
    isolated = build_outer_encoded_features(
        train_keys,
        test_keys,
        fit_idx,
        valid_idx,
        validation_mutated[fit_idx],
        specs,
        level_counts,
        inner_folds,
        seed,
    )[:3]
    validation_isolation = all(
        np.array_equal(left, right) for left, right in zip(original, isolated)
    )

    fit_mutated = y[fit_idx].copy()
    fit_mutated[0] = 1 - fit_mutated[0]
    sensitive = build_outer_encoded_features(
        train_keys,
        test_keys,
        fit_idx,
        valid_idx,
        fit_mutated,
        specs,
        level_counts,
        inner_folds,
        seed,
    )[:3]
    fit_sensitivity = any(
        not np.array_equal(left, right) for left, right in zip(original, sensitive)
    )
    result = {
        "validation_label_mutation_isolated": bool(validation_isolation),
        "outer_fit_label_mutation_changes_encoding": bool(fit_sensitivity),
        "original_digests": [array_digest(array) for array in original],
        "validation_mutated_digests": [array_digest(array) for array in isolated],
    }
    if not validation_isolation or not fit_sensitivity:
        raise AssertionError(f"leakage mutation audit failed: {result}")
    return result


def validate_submission(
    submission: pd.DataFrame, test: pd.DataFrame, sample: pd.DataFrame
) -> None:
    if submission.shape != sample.shape:
        raise ValueError(f"submission shape 错误: {submission.shape} != {sample.shape}")
    if list(submission.columns) != [ID_COL, TARGET]:
        raise ValueError(f"submission columns 错误: {submission.columns.tolist()}")
    if not submission[ID_COL].equals(test[ID_COL]):
        raise ValueError("submission/test id 顺序不一致")
    pred = submission[TARGET].to_numpy(dtype=np.float64)
    if not np.isfinite(pred).all() or ((pred < 0.0) | (pred > 1.0)).any():
        raise ValueError("submission prediction 非法")


def run(args: argparse.Namespace) -> None:
    started = time.time()
    train, test, sample = load_data()
    if args.smoke:
        train, test, sample = smoke_sample(
            train,
            test,
            sample,
            args.smoke_train_rows,
            args.smoke_test_rows,
            args.seed,
        )

    y = train[TARGET].to_numpy(dtype=np.int8)
    # Permanent deletion happens before every feature/key code path.
    train_features = train.drop(columns=[ID_COL, TARGET]).copy()
    test_features = test.drop(columns=[ID_COL]).copy()
    assert_feature_frame(train_features, "main train features")
    assert_feature_frame(test_features, "main test features")

    feature_started = time.time()
    base_train, base_test, base_names = build_base_features(
        train_features, test_features
    )
    train_keys, test_keys, key_specs, level_counts = build_key_codes(
        train_features, test_features
    )
    global_train, global_test, global_names = build_unsupervised_global_frequency(
        train_keys,
        test_keys,
        key_specs,
        level_counts,
    )
    static_feature_seconds = time.time() - feature_started

    outer_folds = args.outer_folds
    inner_folds = args.inner_folds
    splitter = list(
        StratifiedKFold(
            n_splits=outer_folds,
            shuffle=True,
            random_state=args.seed,
        ).split(np.zeros(len(y)), y)
    )

    mutation_audit: dict[str, Any] | None = None
    if args.audit_leakage or args.smoke:
        mutation_audit = leakage_mutation_audit(
            train_keys,
            test_keys,
            y,
            splitter[0][0],
            splitter[0][1],
            key_specs,
            level_counts,
            inner_folds,
            args.seed,
        )
        print(f"[audit] {json.dumps(mutation_audit, ensure_ascii=False)}")

    params: dict[str, Any] = {
        "objective": "binary:logistic",
        "eval_metric": "auc",
        "eta": args.learning_rate,
        "max_depth": args.max_depth,
        "min_child_weight": args.min_child_weight,
        "subsample": 0.90,
        "colsample_bytree": 0.90,
        "colsample_bylevel": 0.90,
        "reg_alpha": 0.10,
        "reg_lambda": 3.0,
        "gamma": 0.0,
        "tree_method": "hist",
        "max_bin": 512,
        "seed": args.seed,
        "nthread": args.nthread,
    }

    oof = np.zeros(len(train), dtype=np.float64)
    test_prediction = np.zeros(len(test), dtype=np.float64)
    fold_scores: list[float] = []
    fold_audits: list[dict[str, Any]] = []
    encoding_seconds: list[float] = []
    training_seconds: list[float] = []
    importance_rows: list[dict[str, Any]] = []
    feature_names: list[str] | None = None

    for fold_number, (fit_idx, valid_idx) in enumerate(splitter, start=1):
        fold_started = time.time()
        encoded_fit, encoded_valid, encoded_test, encoded_names, fold_audit = (
            build_outer_encoded_features(
                train_keys,
                test_keys,
                fit_idx,
                valid_idx,
                y[fit_idx],
                key_specs,
                level_counts,
                inner_folds,
                args.seed,
            )
        )
        encoding_elapsed = time.time() - fold_started
        encoding_seconds.append(encoding_elapsed)

        current_names = base_names + global_names + encoded_names
        if feature_names is None:
            feature_names = current_names
            if len(feature_names) != len(set(feature_names)):
                raise AssertionError("最终特征名不唯一")
            if FORBIDDEN_FEATURES.intersection(feature_names):
                raise AssertionError("最终特征名包含 id/target")
        elif feature_names != current_names:
            raise AssertionError("fold feature names 漂移")

        x_fit = np.column_stack(
            [base_train[fit_idx], global_train[fit_idx], encoded_fit]
        ).astype(np.float32, copy=False)
        x_valid = np.column_stack(
            [base_train[valid_idx], global_train[valid_idx], encoded_valid]
        ).astype(np.float32, copy=False)
        x_test = np.column_stack(
            [base_test, global_test, encoded_test]
        ).astype(np.float32, copy=False)
        if x_fit.shape[1] != len(feature_names):
            raise AssertionError("feature matrix/name 数量不一致")

        dtrain = xgb.DMatrix(
            x_fit,
            label=y[fit_idx],
            feature_names=feature_names,
            nthread=args.nthread,
        )
        dvalid = xgb.DMatrix(
            x_valid,
            label=y[valid_idx],
            feature_names=feature_names,
            nthread=args.nthread,
        )
        dtest = xgb.DMatrix(
            x_test,
            feature_names=feature_names,
            nthread=args.nthread,
        )
        train_started = time.time()
        booster = xgb.train(
            params,
            dtrain,
            num_boost_round=args.num_boost_round,
            evals=[(dvalid, "valid")],
            verbose_eval=args.verbose_eval,
        )
        training_elapsed = time.time() - train_started
        training_seconds.append(training_elapsed)

        valid_prediction = booster.predict(dvalid)
        fold_test_prediction = booster.predict(dtest)
        oof[valid_idx] = valid_prediction
        test_prediction += fold_test_prediction / outer_folds
        fold_auc = float(roc_auc_score(y[valid_idx], valid_prediction))
        fold_scores.append(fold_auc)
        fold_audit.update(
            {
                "fold": fold_number,
                "auc": fold_auc,
                "encoding_seconds": encoding_elapsed,
                "training_seconds": training_elapsed,
            }
        )
        fold_audits.append(fold_audit)

        gain = booster.get_score(importance_type="gain")
        for name in feature_names:
            importance_rows.append(
                {
                    "fold": fold_number,
                    "feature": name,
                    "gain": float(gain.get(name, 0.0)),
                }
            )
        print(
            f"[fold {fold_number}] auc={fold_auc:.6f} "
            f"encode={encoding_elapsed:.1f}s train={training_elapsed:.1f}s "
            f"total={time.time()-fold_started:.1f}s"
        )

        del encoded_fit, encoded_valid, encoded_test
        del x_fit, x_valid, x_test, dtrain, dvalid, dtest, booster
        gc.collect()

    if feature_names is None:
        raise AssertionError("未训练任何 fold")
    oof_auc = float(roc_auc_score(y, oof))
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    np.save(output_dir / "oof_proba.npy", oof)
    np.save(output_dir / "test_proba.npy", test_prediction)
    (output_dir / "feature_names.json").write_text(
        json.dumps(feature_names, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    importance = pd.DataFrame(importance_rows)
    importance_summary = (
        importance.groupby("feature", as_index=False)
        .agg(gain_mean=("gain", "mean"), gain_std=("gain", "std"))
        .sort_values("gain_mean", ascending=False)
    )
    importance_summary.to_csv(output_dir / "feature_importance.csv", index=False)

    submission = sample.copy()
    submission[TARGET] = np.clip(test_prediction, 0.0, 1.0)
    validate_submission(submission, test, sample)
    submission.to_csv(output_dir / "submission.csv", index=False)

    result = {
        "experiment": "v21_xgb_lattice_candidate",
        "mode": "smoke" if args.smoke else "full",
        "created_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "train_rows": int(len(train)),
        "test_rows": int(len(test)),
        "target_mean": float(y.mean()),
        "outer_folds": int(outer_folds),
        "inner_folds": int(inner_folds),
        "seed": int(args.seed),
        "fixed_num_boost_round": int(args.num_boost_round),
        "early_stopping": False,
        "oof_auc": oof_auc,
        "fold_auc": fold_scores,
        "feature_count": int(len(feature_names)),
        "base_feature_count": int(len(base_names)),
        "global_frequency_feature_count": int(len(global_names)),
        "fold_encoding_feature_count": int(2 * len(key_specs)),
        "key_specs": [asdict(spec) for spec in key_specs],
        "fold_audits": fold_audits,
        "leakage_contract": {
            "id_removed_before_all_feature_builders": True,
            "outer_train_encoding": "inner OOF; inner-train labels only",
            "outer_valid_and_test_encoding": "outer-train labels only",
            "combined_train_test_frequency": "feature keys only; no target argument",
            "fixed_rounds_no_outer_checkpoint_selection": True,
            "mutation_audit": mutation_audit,
        },
        "params": params,
        "timing_seconds": {
            "static_feature_build": float(static_feature_seconds),
            "fold_encoding": [float(value) for value in encoding_seconds],
            "xgb_training": [float(value) for value in training_seconds],
            "total": float(time.time() - started),
        },
        "prediction": {
            "oof_min": float(oof.min()),
            "oof_max": float(oof.max()),
            "test_min": float(test_prediction.min()),
            "test_max": float(test_prediction.max()),
            "test_mean": float(test_prediction.mean()),
        },
        "source": {
            "script": str(Path(__file__).resolve()),
            "script_sha256": sha256(Path(__file__).resolve()),
        },
    }
    (output_dir / "cv_results.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        f"[done] mode={result['mode']} OOF={oof_auc:.6f} "
        f"features={len(feature_names)} output={output_dir}"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke", action="store_true", help="small two-fold pipeline")
    parser.add_argument("--audit-leakage", action="store_true")
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--outer-folds", type=int, default=None)
    parser.add_argument("--inner-folds", type=int, default=None)
    parser.add_argument("--num-boost-round", type=int, default=None)
    parser.add_argument("--learning-rate", type=float, default=0.05)
    parser.add_argument("--max-depth", type=int, default=7)
    parser.add_argument("--min-child-weight", type=float, default=8.0)
    parser.add_argument("--nthread", type=int, default=16)
    parser.add_argument("--verbose-eval", type=int, default=None)
    parser.add_argument("--smoke-train-rows", type=int, default=12000)
    parser.add_argument("--smoke-test-rows", type=int, default=4000)
    args = parser.parse_args()

    args.outer_folds = args.outer_folds or (2 if args.smoke else 5)
    args.inner_folds = args.inner_folds or (2 if args.smoke else 5)
    args.num_boost_round = args.num_boost_round or (30 if args.smoke else 1900)
    args.verbose_eval = args.verbose_eval or (10 if args.smoke else 200)
    if args.output_dir is None:
        args.output_dir = (
            Path(tempfile.gettempdir()) / "v21_xgb_lattice_smoke"
            if args.smoke
            else DEFAULT_OUT_DIR
        )
    if args.outer_folds < 2 or args.inner_folds < 2:
        parser.error("outer/inner folds 必须 >= 2")
    if args.num_boost_round <= 0:
        parser.error("num_boost_round 必须 > 0")
    return args


if __name__ == "__main__":
    run(parse_args())
